spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: create
        format_sql: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    suffix: .html   # 파일 확장자
    cache: false
  datasource:
    url: jdbc:mariadb://3.39.233.26:3306/blog
    username: root
    password: 1234
#    url: jdbc:mariadb://localhost:3307/blog
#    username: root
#    password: 0913
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 380797568197-aqhmu0dohaetnlk359gu756tlf9c0ooq.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://kopmorning.com/login/oauth2/code/google
            scope:
              - email
              - profile
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot


file:
#  ImagePath: C:/Users/wnsgh/img/
  ImagePath: /img/